---
all:
  children:
    ubuntu_servers:
      hosts:
        ubuntu-desktop-01:
          ansible_host: 192.168.1.100
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ubuntu-desktop-02:
          ansible_host: 192.168.1.101
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ubuntu-server-01:
          ansible_host: 192.168.1.102
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'